### ISSUE TITLE
"Not all documents in DTM match with a document in the meta data.frame"

### ISSUE THREAD

**Issue by phimeyer** [kasperwelbers/newsflow#2]
Hi,

really a great package. I managed to do a lot with it and without any problems, but since I updated R and RStudio the "newsflow.compare" function didn`t match my dtm with my meta data anymore. 

I checked whether the document_id variable and the document names within the dtm are the same by creating two vectors and check them with a logical operator: 

vec1 <- dtm$dimnames$Docs
vec2 <- data$document_id
vec <-  vec1 %in% vec2

But all document names match with all the document_id. 

It is really strange since the last weeks I was able to operate all functions I want. 

May I send you some example data and my script? 

Best regards

Philipp

**Comment by phimeyer** [comment]
Even a little bit more strange is the fact, that the same problem occurs with older versions of R.

**Comment by kasperwelbers** [comment]
Hi Phillip,

Thanks for contacting me. What error message did you get, specifically?

If it was "'Not all documents in DTM match with a document in the meta data.frame", then this is indeed weird, since your check is very similar to the one yielding that error. The main difference is that I explicitly check for rownames(dtm), and you use the dtm$dimnames$Docs. Could it be that your dtm is a TermDocumentMatrix? To be certain, could you try:

```r
all(rownames(dtm) %in% data$document_id)
```

Alternatively, is your data object a normal data.frame (not, e.g., a list or data.table)?

Kind regards,
Kasper

**Comment by phimeyer** [comment]
Thanks for your response. 

In the early morning I checked whether my meta data is a data.frame or not and it was not, which is also weird because it worked so well in the past. So yeah, a simple as.data.frame transformation solved my problem. 

Thanks a lot for the package.

Kind regards, 

Philipp

**Comment by kasperwelbers** [comment]
Glad that it was so easily solved. I'll make sure to add some class checks in a new update to prevent this sort of confusion in the future.

Best,
Kasper
