### ISSUE TITLE
Identical items

### ISSUE THREAD

**Issue by ruizcrp** [kasperwelbers/newsflow#8]
Hi, this is a really great package. I just started a couple of days ago to experiment with it. I would like to ask a small question.

I have a corpus where several items are absolutely identical (headline and text of article). This is correct as there are several (regional) newspapers belonging to the same owner.

However, it seems to me that he is ignoring pairs that are entirely identical. Could this be? I have also tried with different measures but got the same result. But it could also be that I am doing something wrong.

**Comment by kasperwelbers** [comment]
Hi @ruizcrp. Good to hear that the package is of use to you. 

It should not be the case that identical article are ignored, and I also often encountered identical articles across newspapers in my own research. Perhaps there is another reasons for the identical article pairs (or the specific ones you're looking at) to be missing. Could you share your code? Ideally with some toy data. e.g.

```
m = quanteda::dfm(c('The quick brown fox', 'The quick brown fox', 'The fox jumped over', 'The lazy dog'))
docvars(m, 'date') = seq.POSIXt(as.POSIXct('2010-01-01'), as.POSIXct('2010-01-04'), by='day')
g = compare_documents(m, date_var = 'date', tf_idf=T, hour_window = c(-24,24), only_complete_window = F)
g$d

```

Perhaps a stab in the dark, but there are only a few settings that cause some articles to be ignored. One that can be confusing is that if a time window is used, the earliest and latest articles are removed because they do not have a complete comparison window. In the above example I disabled this with only_complete_window = F. Without this setting, the first two articles will not be compared.
  
```
g = compare_documents(m, date_var = 'date', tf_idf=T, hour_window = c(-24,24))
g$d
```

**Comment by ruizcrp** [comment]
Thank you very much: The stab in the dark hit exactly in the center! :-)
only_complete_window = F made it that these articles were not ignored. It did not have a link with the fact that they were identical!

**Comment by kasperwelbers** [comment]
Great, thanks for confirming!
